### ISSUE TITLE
Login won't stick

### ISSUE THREAD

**Issue by Tibbetts24** [0xW1sKy/Stitch-For-Roku#12]
Login isn't sticking so I deleted the app. Reinstalled.  And still doesn't stick. I leave it for an hour or more and it's not logged in anymore.

**Comment by 0xW1sKy** [comment]
Issue has been identified as a problem with the Refresh Token. Working on fix now.

**Comment by 0xW1sKy** [comment]
I added a new fix in latest release along with other bug fixes. this issue is kinda hard to test so i'll monitor and let you know if i think its gone.

**Comment by Tibbetts24** [comment]
Ok. Thank you!

**Comment by Tibbetts24** [comment]
Still not stcking. Could Twoku somehow be interfering?

**Comment by 0xW1sKy** [comment]
no, its definitely on my end. i've been having trouble getting the login to stick because i'm using a hacky method of handling it to keep it free.

I have a rewrite of the http handler in the 2.0 branch, i'll try backporting that.
