### ISSUE TITLE
Login still not sticking

### ISSUE THREAD

**Issue by Tibbetts24** [0xW1sKy/Stitch-For-Roku#16]
Still not sticking for me. I deleted it, restarted roku, reinstalled,  and after some time went back to it. Nothing.

**Comment by 0xW1sKy** [comment]
So only thing I've seen so far is that it can take a minute for it to complete the login when using a refresh token 🤔


I'm just gonna add a verbose screen so we can see what happens during login.

**Comment by 0xW1sKy** [comment]
okay so here is whats happening. It *IS* properly refreshing tokens now thus logins are technically "sticking"

the current issue is now a race condition where some menus are loading before the login completes. 

after clicking around or going in and out i'm seeing the user info show up correctly. 

I'll see if i can get it to sit in proper order to not confuse end users.
