### ISSUE TITLE
Accessing Any Offline Streamer's Channel Page From The "Following" Menu Causes The App To Force Close

### ISSUE THREAD

**Issue by Insan1ty0ne** [0xW1sKy/Stitch-For-Roku#18]
**Stitch Channel Version:** 1.21 * Build 0
**Roku Device Model:** 9101X - Roku Smart Soundbar
**Roku Software Version:** 11.5.0 * Build 4312-95
**Date Tested:** March 20th 2023
**Description of Issue:** I cannot access any offline streamers channel page. Whenever I try and open an offline streamers page from the "following" tab, the app attempts to load the page and then force closes. This can be repeated over and over and over again with the exact same result. It does not matter which offline streamer's channel I try to access. This makes Stitch completely useless for me versus Twoku. VODs are the number one thing I watch on Twitch as I don't often catch my favorite streamers live. Please fix this.

**Comment by 0xW1sKy** [comment]
This is fixed with 1.33.013 release
