### ISSUE TITLE
Login/Oauth Problem

### ISSUE THREAD

**Issue by Tibbetts24** [0xW1sKy/Stitch-For-Roku#6]
Won't stay logged in. I leave it for a time, go into stitch but I'm no longer signed in.

**Comment by 0xW1sKy** [comment]
Will take a look. 

Can you confirm what model of Roku you have?

**Comment by 0xW1sKy** [comment]
Looking into this. FYI, this will take a day or two of testing to confirm fixed.

**Comment by Tibbetts24** [comment]
I have a Roku Ultra.  Got it this year.

**Comment by 0xW1sKy** [comment]
Issue has been identified and should be fixed in next release

**Comment by Tibbetts24** [comment]
Ok. Thank you!

**Comment by 0xW1sKy** [comment]
Fix for this should be present in v1.5 which was just released.
You can download from [releases](./releases) or update the app via roku.
